services:
  bot:
    build: .
    container_name: scalping_bot
    restart: always
    volumes:
      - .:/usr/src/app
    command: npm start

  hft:
    build: .
    container_name: hft_bot
    restart: always
    volumes:
      - .:/usr/src/app
    command: npm run start-hft

  mm:
    build: .
    container_name: market_making_bot
    restart: always
    volumes:
      - .:/usr/src/app
    command: npm run start-mm

  test:
    build: .
    container_name: order_status_test
    volumes:
      - .:/usr/src/app
    command: node test/checkOrderStatus.js
